# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - master
pr:
  - master

variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make unit-test
      displayName: Run checks and unit test
    - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
      env:
        CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
      displayName: Upload coverage to Codecov

  - job: BDDTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make bddtests
      displayName: Run BDD tests
    - publish: test/bddtests/docker-compose.log
      artifact: docker-compose.log
      condition: always()

  - job: Publish
    dependsOn:
      - UnitTest
      - BDDTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin
          make fabric-peer-docker
          docker tag docker.pkg.github.com/trustbloc/sidetree-fabric/peer:latest  docker.pkg.github.com/trustbloc/sidetree-fabric/peer:$SIDETREE_FABRIC_IMAGE_TAG
          docker push docker.pkg.github.com/trustbloc/sidetree-fabric/peer:$SIDETREE_FABRIC_IMAGE_TAG
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
